---

- hosts: all
  gather_facts: yes
  become: yes
    
  tasks:
    - name: apt update
      apt:
        update_cache: true

- name: Configuring HAproxy loadbalancer
  hosts: HAproxy
  become: yes
  
  tasks:

    
    - name : sudo wait
      become: yes
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
      
    - name: Installing keepalived
      apt:
        name: keepalived
        state: present
        update_cache: true

    - name: sudo sysctl -w net.ipv4.ip_nonlocal_bind=1
      become: yes
      shell: sysctl -w net.ipv4.ip_nonlocal_bind=1

    - name: gather server ip addresses
      setup:
            filter: ansible_default_ipv4.address     
         
    
    - name: copy files haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"
      notify:
        - restart haproxy

         
  - name: "restarting nginx"
    service:
         name: nginx
         state: restarted
         
  handlers:
  - name: "Start HAproxy"
    service:
         name: haproxy
         state: restarted
         
         
- hosts: webservers
  become: yes
  become_method: sudo
  gather_facts: yes
  
  tasks:
  
  
  - name: "update cache"
    apt:
        update_cache: true

  - name: "install pip3"
    apt:
        name: python3-pip
        state: present
        update_cache: true
        
  - name: install flask
    pip: 
      executable: pip3
      name: flask
      state: latest
    
  - name: fetch application
    copy: src=application2.py dest=./application2.py 
    
  - name: "install gunicorn"
    apt:
        name: gunicorn

  - name: "install flask"
    apt:
        name: python3-flask
        
  - name: "install snmpd"
    apt:
        name: snmpd
        state: latest
        
  - name: "Configuring snmpd" 
    template:
         src: "./snmpd.conf"
         dest: "/etc/snmp/snmpd.conf"
    
  - name: "restarting snmpd"
    service:
         name: snmpd
         state: restarted
         enabled: yes

  - name: "copying Application2.py"
    copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        
  - name: "Running Flask app"
    shell: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app
    
    
    
    
